check for exiftool and convert detect missing argument

diff --git a/create-kipi-gallery b/create-kipi-gallery
--- a/create-kipi-gallery
+++ b/create-kipi-gallery
@@ -28,6 +28,12 @@ options:
 __HELPEND
 }
 
+# check dependencies
+
+which exiftool > /dev/null || echo "WARNING: exiftool not found; can't get image descriptions from EXIF; you may want to install the libimage-exiftool-perl package" >&2
+which convert > /dev/null || die "ERROR: convert not found; you need to install the imagemagick package" >&2
+##
+
 while getopts "s:t:on:d:T:h" opt; do
 	case $opt in
 		s)
@@ -57,6 +63,8 @@ while getopts "s:t:on:d:T:h" opt; do
   		esac
 done
 shift $((OPTIND-1))
+
+[[ -z $1 ]] && { help; exit 1; }
 
 DIR=$1
 [[ $THUMBSIZE -gt 0 ]] || die "invalid thumbnail size"
