use "i" for the name for the images subdirectory
Don't use the gallery name for the image subdirectory as this may contain
special characters not allowed/sensible for filenames. Use a short one-letter
name "i" instead.

diff --git a/create-kipi-gallery b/create-kipi-gallery
--- a/create-kipi-gallery
+++ b/create-kipi-gallery
@@ -76,8 +76,8 @@ echo '<?xml version="1.0" encoding="UTF-8"?>'
 echo '<collections>'
 echo '<collection>'
 echo "<name>$GALNAME</name>"
-echo "<fileName>$GALNAME</fileName>"
-mkdir "$GALDIR/$GALNAME" || die "cannot create directory"
+echo "<fileName>i</fileName>"
+mkdir "$GALDIR/i" || die "cannot create directory"
 
 {
 	if [[ -f $DIR/index ]]; then
@@ -92,10 +92,10 @@ mkdir "$GALDIR/$GALNAME" || die "cannot create directory"
 	echo "processing $ORIG" >&2
 	echo '<image>'
 
-	CONVRES=`convert -auto-orient -resize "${FULLSIZE}x${FULLSIZE}>" -identify -format "%[width] %[height] %w %h" "$ORIG" "$GALDIR/$GALNAME/$f" 2>&1`
+	CONVRES=`convert -auto-orient -resize "${FULLSIZE}x${FULLSIZE}>" -identify -format "%[width] %[height] %w %h" "$ORIG" "$GALDIR/i/$f" 2>&1`
 	read OW OH FW FH <<<"$CONVRES"
 
-	CONVRES=`convert -auto-orient -resize ${THUMBSIZE}x${THUMBSIZE} -identify -format "%w %h" "$ORIG" "$GALDIR/$GALNAME/thumb_$f" 2>&1`
+	CONVRES=`convert -auto-orient -resize ${THUMBSIZE}x${THUMBSIZE} -identify -format "%w %h" "$ORIG" "$GALDIR/i/thumb_$f" 2>&1`
 	read TW TH <<<"$CONVRES"
 
 
@@ -104,7 +104,7 @@ mkdir "$GALDIR/$GALNAME" || die "cannot create directory"
 	echo "<full fileName=\"$f\" width=\"$FW\" height=\"$FH\"/>"
 	echo "<thumbnail fileName=\"thumb_$f\" width=\"$TW\" height=\"$TH\"/>"
 	if $ORIGINAL; then
-		cp "$ORIG" "$GALDIR/$GALNAME/original_$f"
+		cp "$ORIG" "$GALDIR/i/original_$f"
 		echo "<original fileName=\"original_$f\" width=\"$OW\" height=\"$OH\"/>"
 	fi
 	echo '</image>'
